import { EmailLabel } from "@/data/emails";

interface ChoiceButtonsProps {
  selected: EmailLabel | null;
  onSelect: (label: EmailLabel) => void;
  disabled?: boolean;
}

const choices: { label: EmailLabel; description: string }[] = [
  { label: "Human", description: "Written entirely by a human" },
  { label: "AI", description: "Generated by AI" },
  { label: "Edited by AI", description: "AI-assisted or edited" },
];

export function ChoiceButtons({ selected, onSelect, disabled }: ChoiceButtonsProps) {
  return (
    <div className="grid grid-cols-3 gap-3">
      {choices.map((c) => (
        <button
          key={c.label}
          onClick={() => onSelect(c.label)}
          disabled={disabled}
          className={`flex flex-col items-center gap-2 rounded-lg border p-4 transition-colors ${
            selected === c.label
              ? "border-foreground bg-muted"
              : "border-border bg-card hover:border-muted-foreground/50"
          } ${disabled ? "opacity-50 cursor-not-allowed" : "cursor-pointer"}`}
        >
          <span className={`text-sm font-medium ${selected === c.label ? "text-foreground" : "text-muted-foreground"}`}>
            {c.label}
          </span>
          <span className="text-xs text-muted-foreground text-center">{c.description}</span>
        </button>
      ))}
    </div>
  );
}
