import { EmailLabel } from "@/data/emails";
import { User, Bot } from "lucide-react";

interface ChoiceButtonsProps {
  selected: EmailLabel | null;
  onSelect: (label: EmailLabel) => void;
  disabled?: boolean;
}

const choices: { label: EmailLabel; icon: React.ReactNode; description: string }[] = [
  { label: "Human", icon: <User className="w-5 h-5" />, description: "Written entirely by a human" },
  { label: "AI", icon: <Bot className="w-5 h-5" />, description: "Generated by AI" },
];

export function ChoiceButtons({ selected, onSelect, disabled }: ChoiceButtonsProps) {
  return (
    <div className="grid grid-cols-2 gap-3">
      {choices.map((c) => (
        <button
          key={c.label}
          onClick={() => onSelect(c.label)}
          disabled={disabled}
          className={`flex flex-col items-center gap-2 rounded-lg border p-4 transition-all duration-200 ${
            selected === c.label
              ? "border-primary bg-primary/10 ring-2 ring-primary/30 shadow-lg shadow-primary/10"
              : "border-border bg-card hover:border-muted-foreground/30 hover:bg-muted/50"
          } ${disabled ? "opacity-50 cursor-not-allowed" : "cursor-pointer"}`}
        >
          <div className={selected === c.label ? "text-primary" : "text-muted-foreground"}>{c.icon}</div>
          <span className={`text-sm font-medium ${selected === c.label ? "text-primary" : "text-foreground"}`}>
            {c.label}
          </span>
          <span className="text-xs text-muted-foreground text-center">{c.description}</span>
        </button>
      ))}
    </div>
  );
}
